Adding dev server config
BigZeta/generator-bz-react-component pull request #3
Opened 2017-05-25 05:19 UTC by jdltechworks

@kutenai 

Added codes to make the devserver to use the dev configuration

2017-05-26 04:59 UTC, kutenai commented
Please use paths

2017-05-26 15:37 UTC, kutenai requested changes

2017-05-26 15:37 UTC, kutenai commented on generators/app/templates/config/dev.js
> -paths.build = path.resolve('../dist.dev');
I keep adding this and then you go in and remove it... stop doing that

2017-05-26 15:37 UTC, kutenai commented on generators/app/templates/config/dev.js
> +                path: resolve('dist.dev/js'),
I don't want to see hard-code paths!

2017-05-26 15:37 UTC, kutenai commented on generators/app/templates/config/dev.js
> +                    path: resolve('dist.dev'),
Hard coded path

2017-05-26 15:37 UTC, kutenai commented on generators/app/templates/config/dev.js
> +                    join(__dirname, '../dev/index.js'),
Hard coded path..
join(path.dev, 'index.js') would be better

2017-05-26 15:37 UTC, kutenai commented on generators/app/templates/config/devserver.js
> +                    join(__dirname, '../dev/index.js')
join(paths.dev, 'index.js')

2017-05-26 15:37 UTC, kutenai commented on generators/app/templates/config/devserver.js
> +        partials.htmlWebpack('./dev/templates')
join(paths.dev, 'templates')

2017-05-26 15:37 UTC, kutenai commented on generators/app/templates/config/partials.js
>              template: path.join(__dirname, '../dev/templates/index.ejs'),
join(paths.dev, 'templates/index.ejs')

2017-05-26 15:37 UTC, kutenai commented on generators/app/templates/webpack.config.babel.js
> +    const serve = env.includes('serve')
Why do this? 
I already had a mechanism where we can merge and override previous configs.. so, we can have a devserver.js that merges in additional stuff on top of dev.src, we don't need this extra stuff here.

this is inconsistent with the rest of the logic. The logic is "dev" specifies the filename, I don't want a "special case" for server.. special cases are not special, they are bad.

2017-05-29 10:10 UTC, jdltechworks commented
@kutenai 

Removed hardcoded paths and special case in the webpack.config.babel.js

included options to use the devserver config

2017-05-30 23:26 UTC, merged